services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurmdbpass
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - slurmnet

  slurmdbd:
    container_name: slurmdbd
    hostname: slurmdbd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/etc/slurm
      - slurmdbd_logs:/var/log
      - slurmdbd_run:/var/run
      - munge_key:/etc/munge
    command: ["slurmdbd", "-Dvvv"]
    depends_on:
      - mariadb
    networks:
      - slurmnet

  slurmctld:
    container_name: slurmctld
    hostname: slurmctld
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/etc/slurm
      - slurmctld_state:/var/spool/slurm
      - slurmctld_logs:/var/log
      - slurmctld_run:/var/run
      - munge_key:/etc/munge
    command: ["slurmctld", "-Dvvv"]
    depends_on:
      - slurmdbd
    networks:
      - slurmnet

  c1:
    container_name: c1
    hostname: c1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/etc/slurm
      - c1_spool:/var/spool/slurmd
      - c1_logs:/var/log
      - c1_run:/var/run
      - munge_key:/etc/munge
    command: ["slurmd", "-Dvvv"]
    depends_on:
      - slurmctld
    deploy:
      resources:
        limits:
          cpus: "2.0"
    networks:
      - slurmnet

volumes:
  mariadb:
  slurmdbd_logs:
  slurmdbd_run:
  slurmctld_state:
  slurmctld_logs:
  slurmctld_run:
  c1_spool:
  c1_logs:
  c1_run:
  munge_key:

networks:
  slurmnet:
