services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurmdbpass
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - slurmnet

  slurmdbd:
    build:
      context: .
    image: slurm-docker-slurmdbd
    depends_on:
      - mariadb
    volumes:
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
    command: slurmdbd
    networks:
      - slurmnet

  slurmctld:
    build:
      context: .
    image: slurm-docker-slurmctld
    depends_on:
      - slurmdbd
    volumes:
      - ./slurm.conf:/etc/slurm/slurm.conf
    command: slurmctld
    networks:
      - slurmnet

  c1:
    hostname: c1

    build:
      context: .
    image: slurm-docker-c1
    depends_on:
      - slurmctld
    volumes:
      - ./slurm.conf:/etc/slurm/slurm.conf
    command: slurmd
    networks:
      - slurmnet

volumes:
  mariadb:

networks:
  slurmnet:
