# version: "3.9"

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: slurm_acct_db
      MARIADB_USER: slurm
      MARIADB_PASSWORD: slurmdbpass
    networks:
      - slurmnet

  slurmdbd:
    build: .
    hostname: slurmdbd
    environment:
      - SLURMDBD=yes
    depends_on:
      - mariadb
    volumes:
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
    command: >
      /bin/bash -c "chmod 600 /etc/slurm/slurmdbd.conf && /entrypoint.sh"
    networks:
      - slurmnet

  slurmctld:
    build: .
    hostname: slurmctld
    depends_on:
      - slurmdbd
    environment:
      - SLURMCTLD=yes
    volumes:
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    networks:
      - slurmnet

  c1:
    build: .
    hostname: c1
    depends_on:
      - slurmctld
    environment:
      - SLURMD=yes
    volumes:
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    networks:
      - slurmnet

networks:
  slurmnet:
